keys:
    - &user_paul 8D1060B96BB8292E829B7249AED41CC193B701E2
    - &user_paul_age age1peu96695en0xrlshkd3j3zzd04payh3cx27yjw6r40z8ekemnuesmkrupn
    - &host_prematurata 8C3E4F6EB38828939029AE7BE9B6AF0CD39DD935
    - &host_frastanato age1puglnvqv3h0r456rjqwyc2ggn545gagkheqt3r34rnnp7lc3rcas5vp2rx
    - &host_virtual_nellone 0F2BE5B4330DB4B040BCCA09993D2403D1A5C448

creation_rules:
    - path_regex: .*common\.yaml$
      key_groups:
          - age:
                - *user_paul_age
                - *host_frastanato
            pgp:
                - *user_paul
                - *host_prematurata
    - path_regex: .*prematurata\.yaml$
      key_groups:
          - pgp:
                - *user_paul
                - *host_prematurata
    - path_regex: .*frastanato\.yaml$
      key_groups:
          - age:
                - *user_paul_age
                - *host_frastanato
    - path_regex: .*virtual_nellone\.yaml$
      key_groups:
          - pgp:
                - *user_paul
                - *host_virtual_nellone
