(define jdk-version "17")

(use-modules (gnu packages gcc))

(packages->manifest
  (append
    (list (make-libstdc++ gcc))
    (map specification->package+output
       `(,(string-append "openjdk@" jdk-version)
         ,(string-append "openjdk@" jdk-version ":jdk")
         "alsa-lib"
         "at-spi2-atk"
         "at-spi2-core"
         "atk"
         "bash-minimal"
         "cairo"
         "coreutils"
         "dbus"
         "e2fsprogs"
         "eudev"
         "expat"
         "findutils"
         "fontconfig"
         "freetype"
         "git"
         "glib"
         "grep"
         "gtk+"
         "libdrm"
         "libgccjit"
         "libnotify"
         "librsvg"
         "libsecret"
         "libx11"
         "libxcb"
         "libxcomposite"
         "libxcursor"
         "libxdamage"
         "libxext"
         "libxfixes"
         "libxi"
         "libxkbcommon"
         "libxkbfile"
         "libxrandr"
         "libxrender"
         "libxshmfence"
         "libxtst"
         "mesa"
         "nspr"
         "nss"
         "pango"
         "pulseaudio"
         "qemu-minimal"
         "sed"
         "util-linux:lib"
         "xcb-util"
         "xcb-util-image"
         "xcb-util-keysyms"
         "xcb-util-renderutil"
         "xcb-util-wm"
         "which"
         "zlib"))))
