#!/usr/bin/env sh

set -eu

[ "$#" -ne 2 ] && echo "Usage: $(basename "$0") OPERATING-SYSTEM-NAME CONFIG-PATH" >&2 && exit 1


set -x

system_name="$1"
config_path="$2"

tmp_config="/tmp/config.scm"

head -n -1 "${config_path}" > "$tmp_config"
echo "$system_name" >> "$tmp_config"
